# 1. Tensors

In [9]:
import torch

In [86]:
x = torch.tensor([[1., 2., 3.], [4., 5., 6.]])
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


### Checking properties

In [20]:
x.dim()

2

In [21]:
x.shape

torch.Size([2, 3])

In [22]:
x.size()

torch.Size([2, 3])

### Operations

In [23]:
torch.sum(x, dim=1)

tensor([ 6., 15.])

In [24]:
x.sum(dim=1)

tensor([ 6., 15.])

Example - Computing the norm: $$\sqrt{x_1^2 + x_2^2 + \dots + x_n^2}$$

In [30]:
# (x**2).sum().sqrt()
# x.norm(p=2)

tensor(9.5394)

### In-Place Operators

All element-wise functions have an inplace version

In [37]:
A = torch.eye(3)
A

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [38]:
A.add(5)

tensor([[6., 5., 5.],
        [5., 6., 5.],
        [5., 5., 6.]])

In [39]:
A

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [40]:
A.add_(5)

tensor([[6., 5., 5.],
        [5., 6., 5.],
        [5., 5., 6.]])

In [ ]:
A

Note:

In [33]:
A = torch.ones(1)

A_before = A
A = A + 1

print(A, A_before)

tensor([2.]) tensor([1.])


In [34]:
A = torch.ones(1)

A_before = A
A += 1

print(A, A_before)

tensor([2.]) tensor([2.])


### Reshaping

In Pytorch, we use the `view` function to reshape a tensor.  

In [50]:
X = torch.tensor([1, 2, 3, 4, 5, 6])
print(X)

tensor([1, 2, 3, 4, 5, 6])


In [47]:
X.view(2, 3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [48]:
X.view(-1, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

It does not create a copy: different views _share the same data._  
A function `reshape` exists but it performs a copy of the Tensor.

### Type Conversion

In [52]:
Y = 4 * torch.rand((2,4))

In [53]:
Y.dtype

torch.float32

In [54]:
Y.to(torch.float16)

tensor([[1.8145, 3.0898, 1.6445, 3.2285],
        [2.8281, 0.6250, 1.0547, 3.7871]], dtype=torch.float16)

In [55]:
Y.to(torch.int64)

tensor([[1, 3, 1, 3],
        [2, 0, 1, 3]])

### Using a GPU

In [ ]:
torch.cuda.is_available()  # Check if we can use GPUs

In [ ]:
x = torch.Tensor([[1,2,3], [4,5,6]])

#### The **old** way

In [78]:
y = x.cuda()
print(y)

AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx

In [79]:
y = x.cpu()
print(y)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


#### The **new** way

In [83]:
# Define the device
dev_cpu = torch.device("cpu")
dev_gpu = torch.device("cuda:0")

In [84]:
x.to(dev_cpu)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [82]:
# At the beginning of your code
device = torch.device("cpu" if not torch.cuda.is_available() else "cuda")

# Later in the code
x.to(device)

### PyTorch <--> Numpy

In [74]:
import numpy as np

X = np.random.random((2,3))
print(X)

[[0.4022175  0.08150012 0.99686401]
 [0.09889246 0.79265983 0.50987632]]


In [75]:
# numpy ---> torch
Y = torch.from_numpy(X)
print(Y)

tensor([[0.4022, 0.0815, 0.9969],
        [0.0989, 0.7927, 0.5099]], dtype=torch.float64)


In [76]:
# torch ---> numpy
X = Y.numpy()
print(X)

[[0.4022175  0.08150012 0.99686401]
 [0.09889246 0.79265983 0.50987632]]


## Building our training loop (1 / 5)

In [1]:
# INITIALIZATION

import torch

device = torch.device("cpu")

In [7]:
# TRAINING LOOP

# Loop through dataset to get sample and label
    sample = sample.to(device)
    label = label.to(device)
    # compute predictions with model
    # compute the loss
    # compute gradients
    # update model parameters